version: '3'

services:
    php:
        build: docker/php
        volumes:
            - .:/var/www/html
        ports:
            - 8000:80
        container_name: php7.2-trial2
        restart: always
        links:
            - mysql

    mysql:
        image: mysql:5.7
        volumes:
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=root
        container_name: mysql5.7-trial2

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql #mysqlサービス名を指定
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - mysql
        ports:
            - 4040:80
        volumes:
            - ./phpmyadmin/sessions:/sessions
